import "src/styles/globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import { Footer, Navbar } from "@/components";
// import Products from "./products-client/page";
// import { HomePage } from "./page";
import "./page.css"


const roboto_mono = Roboto_Mono({
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto_mono.className}>
        <Navbar />
        {children}
        {/* <div className="home-products" /> */}
        <Footer />
      </body>
    </html>
  );
}
