import "src/styles/globals.css";
import type { Metadata } from "next";
import { Footer, Navbar } from "@/components";
import { StoreProvider } from "@/store/StoreProvider";
import { fira } from "@/components/ui/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className}>
        <StoreProvider>
          <Navbar />
          {children}
          <Footer />
        </StoreProvider>
      </body>
    </html>
  );
}
